# Generated by Django 3.2.4 on 2021-06-30 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/category')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('description', models.TextField(max_length=255)),
                ('company', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=155)),
                ('phone', models.CharField(blank=True, max_length=155)),
                ('email', models.CharField(blank=True, max_length=155)),
                ('icon', models.ImageField(blank=True, upload_to='media/images/')),
                ('facebook', models.CharField(blank=True, max_length=155)),
                ('instagram', models.CharField(blank=True, max_length=155)),
                ('twitter', models.CharField(blank=True, max_length=155)),
                ('youtube', models.CharField(blank=True, max_length=155)),
                ('aboutus', models.TextField(blank=True)),
                ('contact', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='images/product')),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.category')),
            ],
        ),
    ]
