# Generated by Django 3.2.4 on 2021-07-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_shopcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
